name: 'CI'
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests 
        uses: actions/checkout@v2         # checkout the repo
      - run: "pip install pytest"
      - run: "py.test --junitxml test_results.xml my_test.py"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'test_results.xml'
