name: 'CI'
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests 
        uses: actions/checkout@v2         # checkout the repo
      - run: "pip install pytest"
      - run: "py.test --junitxml test_results.xml my_test.py"
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always() # always run even if the previous step fails
        with:
          name: JEST Tests
          path: 'test_results.xml'
          reporter: jest-junit
