name: 'CI'
on: [push]
jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Run tests 
        uses: actions/checkout@v2         # checkout the repo
      - run: "python ./my_test.py"
